import type {
  AnalyticsEvent,
  CtaButton,
  LandingPageSection,
  ResponsiveSetting,
  SeoMetadata,
  SiteLogo,
  Testimonial,
} from "@/types";

export const mockLandingPageSectionList: LandingPageSection[] = [
  {
    id: "section-hero",
    type: "hero",
    name: "Hero 섹션",
    title: "가구 가격, 매장 가기 전에 비교하세요",
    subtitle: "원하는 가구를 합리적으로 비교하고 내게 맞는 제품을 찾아보세요.",
    content: "",
    points: [],
    order: 0,
    route: "/hero",
    nextRoute: "/screen",
    ctaLabel: "무료로 시작하기",
    ctaId: "cta-hero-start",
    status: "published",
    updatedAt: "2026-09-15T09:00:00+09:00",
  },
  {
    id: "section-problem",
    type: "problem",
    name: "문제 제시 섹션",
    title: "가구 비교, 왜 이렇게 번거로울까요?",
    subtitle: "제품마다 가격을 확인하기 어렵고, 비교하려면 여러 매장을 직접 방문해야 합니다.",
    content: "",
    points: [
      {
        id: "problem-price",
        title: "한눈에 보기 어려운 가격",
        description: "마음에 드는 가구를 찾아도 제품별 가격을 비교하려면 여러 곳을 따로 확인해야 합니다.",
        icon: "Tags",
      },
      {
        id: "problem-visits",
        title: "계속 늘어나는 매장 방문",
        description: "내게 맞는 제품인지 알아보려 여러 매장을 오가는 데 많은 시간과 수고가 듭니다.",
        icon: "MapPin",
      },
    ],
    order: 1,
    route: "/screen",
    nextRoute: "/screen-2",
    ctaLabel: "계속",
    ctaId: "cta-problem-next",
    status: "published",
    updatedAt: "2026-09-15T09:05:00+09:00",
  },
  {
    id: "section-solution",
    type: "solution",
    name: "서비스 소개 섹션",
    title: "가구 선택, 비교부터 더 간단하게",
    subtitle: "원하는 조건에 맞춰 가격을 비교하고, 나에게 맞는 가구를 찾아보세요.",
    content: "여러 매장을 직접 둘러보는 번거로움을 줄이고 합리적인 구매를 돕습니다.",
    points: [
      {
        id: "solution-find",
        title: "원하는 가구 찾기",
        description: "필요한 가구와 원하는 조건을 기준으로 살펴보세요.",
        icon: "Search",
      },
      {
        id: "solution-compare",
        title: "가격 비교하기",
        description: "여러 제품의 가격을 한눈에 비교해 보세요.",
        icon: "ArrowLeftRight",
      },
      {
        id: "solution-choose",
        title: "알맞은 제품 고르기",
        description: "조건과 가격을 함께 살펴보고 나에게 맞는 제품을 선택하세요.",
        icon: "CircleCheck",
      },
    ],
    order: 2,
    route: "/screen-2",
    nextRoute: "/screen-3",
    ctaLabel: "계속",
    ctaId: "cta-solution-next",
    status: "published",
    updatedAt: "2026-09-15T09:10:00+09:00",
  },
  {
    id: "section-benefits",
    type: "benefits",
    name: "핵심 장점 섹션",
    title: "가구 비교, 더 간단하게",
    subtitle: "가격부터 필요한 조건까지 살펴보고 나에게 맞는 가구를 찾아보세요.",
    content: "",
    points: [
      {
        id: "benefit-price",
        title: "가격을 쉽게 비교하세요",
        description: "여러 가구의 가격을 한눈에 살펴보고 합리적으로 선택하세요.",
        icon: "BadgeWon",
      },
      {
        id: "benefit-fit",
        title: "내게 맞는 제품을 찾으세요",
        description: "원하는 조건과 가격을 함께 비교해 필요한 가구를 골라보세요.",
        icon: "SlidersHorizontal",
      },
      {
        id: "benefit-visits",
        title: "매장 방문을 줄이세요",
        description: "방문 전에 충분히 비교하고 더 편리하게 구매를 결정하세요.",
        icon: "Route",
      },
    ],
    order: 3,
    route: "/screen-3",
    nextRoute: "/cta",
    ctaLabel: "계속",
    ctaId: "cta-benefits-next",
    status: "published",
    updatedAt: "2026-09-15T09:15:00+09:00",
  },
  {
    id: "section-cta",
    type: "cta",
    name: "최종 CTA 섹션",
    title: "내게 맞는 가구, 합리적인 비교에서 시작하세요",
    subtitle: "원하는 가구를 편리하게 비교하고 매장 방문의 번거로움을 줄여보세요.",
    content: "",
    points: [],
    order: 4,
    route: "/cta",
    nextRoute: null,
    ctaLabel: "기획안 만들기",
    ctaId: "cta-final-start",
    status: "published",
    updatedAt: "2026-09-15T09:20:00+09:00",
  },
];

export const mockTestimonialList: Testimonial[] = [
  {
    id: "testimonial-001",
    quote: "소파를 보러 매장마다 전화하던 대신 후보 제품의 가격을 먼저 비교할 수 있어 선택이 훨씬 수월했어요.",
    author: "김민지",
    authorContext: "신혼 거실 가구 구매",
    result: "매장 방문 4회에서 1회로 감소",
    rating: 5,
    status: "approved",
    createdAt: "2026-08-20T11:30:00+09:00",
    decidedAt: "2026-08-21T10:00:00+09:00",
  },
  {
    id: "testimonial-002",
    quote: "비슷해 보이는 식탁도 가격 차이가 컸는데 조건과 가격을 같이 보니 예산에 맞는 제품을 빠르게 찾았습니다.",
    author: "박준호",
    authorContext: "4인용 식탁 구매",
    result: "비교 후보 8개에서 최종 2개로 정리",
    rating: 5,
    status: "approved",
    createdAt: "2026-08-25T14:20:00+09:00",
    decidedAt: "2026-08-26T09:40:00+09:00",
  },
  {
    id: "testimonial-003",
    quote: "아이 방 책상을 고를 때 크기와 가격을 한 번에 확인해서 주말마다 매장을 도는 수고를 줄였어요.",
    author: "이서연",
    authorContext: "자녀 방 가구 구매",
    result: "주말 매장 방문 3회에서 1회로 감소",
    rating: 5,
    status: "approved",
    createdAt: "2026-08-29T16:10:00+09:00",
    decidedAt: "2026-08-30T10:15:00+09:00",
  },
  {
    id: "testimonial-004",
    quote: "수납장 폭과 예산에 맞는 제품만 추려서 확인하니 매장에서는 실물과 마감만 집중해서 볼 수 있었습니다.",
    author: "최현우",
    authorContext: "이사 가구 구매",
    result: "매장 체류 시간 3시간에서 1시간으로 감소",
    rating: 4,
    status: "approved",
    createdAt: "2026-09-02T13:45:00+09:00",
    decidedAt: "2026-09-03T11:00:00+09:00",
  },
  {
    id: "testimonial-005",
    quote: "침대 프레임을 브랜드별로 따로 찾지 않고 가격대를 비교할 수 있어서 구매 기준을 세우기 편했어요.",
    author: "정유진",
    authorContext: "침실 가구 교체",
    result: "비교 시간 이틀에서 반나절로 감소",
    rating: 4,
    status: "pending",
    createdAt: "2026-09-18T09:25:00+09:00",
    decidedAt: null,
  },
];

export const mockAnalyticsEventList: AnalyticsEvent[] = [
  {
    id: "event-001",
    name: "page_view",
    pagePath: "/hero",
    occurredAt: "2026-09-20T09:00:00+09:00",
    ctaId: null,
    label: null,
  },
  {
    id: "event-002",
    name: "cta_click",
    pagePath: "/hero",
    occurredAt: "2026-09-20T09:01:20+09:00",
    ctaId: "cta-hero-start",
    label: "무료로 시작하기",
  },
  {
    id: "event-003",
    name: "page_view",
    pagePath: "/screen",
    occurredAt: "2026-09-20T09:01:21+09:00",
    ctaId: null,
    label: null,
  },
  {
    id: "event-004",
    name: "cta_click",
    pagePath: "/screen",
    occurredAt: "2026-09-20T09:02:10+09:00",
    ctaId: "cta-problem-next",
    label: "계속",
  },
  {
    id: "event-005",
    name: "page_view",
    pagePath: "/screen-2",
    occurredAt: "2026-09-20T09:02:11+09:00",
    ctaId: null,
    label: null,
  },
  {
    id: "event-006",
    name: "cta_click",
    pagePath: "/screen-2",
    occurredAt: "2026-09-20T09:03:05+09:00",
    ctaId: "cta-solution-next",
    label: "계속",
  },
  {
    id: "event-007",
    name: "page_view",
    pagePath: "/screen-3",
    occurredAt: "2026-09-20T09:03:06+09:00",
    ctaId: null,
    label: null,
  },
  {
    id: "event-008",
    name: "cta_click",
    pagePath: "/screen-3",
    occurredAt: "2026-09-20T09:04:00+09:00",
    ctaId: "cta-benefits-next",
    label: "계속",
  },
  {
    id: "event-009",
    name: "page_view",
    pagePath: "/cta",
    occurredAt: "2026-09-20T09:04:01+09:00",
    ctaId: null,
    label: null,
  },
  {
    id: "event-010",
    name: "page_view",
    pagePath: "/",
    occurredAt: "2026-09-21T15:30:00+09:00",
    ctaId: null,
    label: null,
  },
];

export const mockLogoList: SiteLogo[] = [
  {
    id: "logo-main-combined",
    name: "가구비교",
    shortName: "가비",
    alt: "가구비교 홈",
    href: "/",
    variant: "combined",
    status: "active",
  },
  {
    id: "logo-home-wordmark",
    name: "가구비교",
    shortName: "가비",
    alt: "가구비교 서비스",
    href: "/",
    variant: "wordmark",
    status: "inactive",
  },
  {
    id: "logo-home-icon",
    name: "가구비교",
    shortName: "가비",
    alt: "가구비교 시작 화면",
    href: "/hero",
    variant: "icon",
    status: "inactive",
  },
  {
    id: "logo-hero-combined",
    name: "가구비교",
    shortName: "가비",
    alt: "가구비교 소개",
    href: "/hero",
    variant: "combined",
    status: "inactive",
  },
  {
    id: "logo-cta-wordmark",
    name: "가구비교",
    shortName: "가비",
    alt: "가구비교 대표 페이지",
    href: "/",
    variant: "wordmark",
    status: "inactive",
  },
];

export const mockResponsiveSettingList: ResponsiveSetting[] = [
  {
    id: "responsive-mobile-compact",
    device: "mobile",
    label: "소형 모바일",
    minWidth: 0,
    maxWidth: 374,
    description: "콘텐츠와 CTA를 한 열로 배치하고 긴 문구를 자연스럽게 줄바꿈합니다.",
    browsers: ["모바일 Safari", "모바일 Chrome"],
    columns: 1,
    support: "supported",
  },
  {
    id: "responsive-mobile",
    device: "mobile",
    label: "모바일",
    minWidth: 375,
    maxWidth: 639,
    description: "핵심 콘텐츠 순서를 유지하며 버튼을 터치하기 쉬운 크기로 표시합니다.",
    browsers: ["모바일 Safari", "모바일 Chrome", "Samsung Internet"],
    columns: 1,
    support: "supported",
  },
  {
    id: "responsive-tablet",
    device: "tablet",
    label: "태블릿",
    minWidth: 640,
    maxWidth: 1023,
    description: "설명 항목을 최대 두 열로 구성하고 본문 읽기 폭을 안정적으로 유지합니다.",
    browsers: ["Safari", "Chrome", "Edge"],
    columns: 2,
    support: "supported",
  },
  {
    id: "responsive-desktop",
    device: "desktop",
    label: "데스크톱",
    minWidth: 1024,
    maxWidth: 1439,
    description: "설명 항목을 최대 세 열로 배치하고 주요 CTA를 명확하게 구분합니다.",
    browsers: ["Chrome", "Safari", "Edge", "Firefox"],
    columns: 3,
    support: "supported",
  },
  {
    id: "responsive-desktop-wide",
    device: "desktop",
    label: "대형 데스크톱",
    minWidth: 1440,
    maxWidth: null,
    description: "본문 최대 폭을 유지해 지나치게 긴 행을 방지하고 여백을 넉넉하게 표시합니다.",
    browsers: ["Chrome", "Safari", "Edge", "Firefox"],
    columns: 3,
    support: "supported",
  },
];

export const mockSeoMetadataList: SeoMetadata[] = [
  {
    id: "seo-home",
    pagePath: "/",
    title: "가구비교 | 원하는 가구를 합리적으로 비교하세요",
    description: "가구 가격과 필요한 조건을 편리하게 비교하고 내게 맞는 제품을 찾아보세요.",
    canonicalUrl: "/",
    lang: "ko",
    robots: "index,follow",
    ogTitle: "원하는 가구를 합리적으로 비교하세요",
    ogDescription: "가격과 조건을 살펴보고 매장 방문 전에 내게 맞는 가구를 찾아보세요.",
    status: "applied",
  },
  {
    id: "seo-hero",
    pagePath: "/hero",
    title: "가구 가격 비교 시작 | 가구비교",
    description: "원하는 가구를 합리적으로 비교하고 내게 맞는 제품을 찾아보세요.",
    canonicalUrl: "/hero",
    lang: "ko",
    robots: "index,follow",
    ogTitle: "가구 가격, 매장 가기 전에 비교하세요",
    ogDescription: "원하는 가구를 합리적으로 비교하고 내게 맞는 제품을 찾아보세요.",
    status: "applied",
  },
  {
    id: "seo-problem",
    pagePath: "/screen",
    title: "번거로운 가구 비교 줄이기 | 가구비교",
    description: "제품별 가격 확인과 반복되는 매장 방문이 왜 번거로운지 살펴보세요.",
    canonicalUrl: "/screen",
    lang: "ko",
    robots: "index,follow",
    ogTitle: "가구 비교, 왜 이렇게 번거로울까요?",
    ogDescription: "여러 곳의 가격을 따로 확인하고 매장을 방문하는 번거로움을 줄여보세요.",
    status: "applied",
  },
  {
    id: "seo-solution",
    pagePath: "/screen-2",
    title: "간단한 가구 가격 비교 방법 | 가구비교",
    description: "원하는 조건에 맞춰 가격을 비교하고 나에게 맞는 가구를 찾는 방법을 확인하세요.",
    canonicalUrl: "/screen-2",
    lang: "ko",
    robots: "index,follow",
    ogTitle: "가구 선택, 비교부터 더 간단하게",
    ogDescription: "여러 제품의 조건과 가격을 한눈에 비교하고 알맞은 가구를 선택하세요.",
    status: "applied",
  },
  {
    id: "seo-benefits",
    pagePath: "/screen-3",
    title: "가구 비교의 핵심 장점 | 가구비교",
    description: "가격과 조건을 함께 비교해 제품 선택과 매장 방문의 부담을 줄여보세요.",
    canonicalUrl: "/screen-3",
    lang: "ko",
    robots: "index,follow",
    ogTitle: "가구 비교, 더 간단하게",
    ogDescription: "가격부터 필요한 조건까지 살펴보고 나에게 맞는 가구를 찾아보세요.",
    status: "applied",
  },
  {
    id: "seo-cta",
    pagePath: "/cta",
    title: "내게 맞는 가구 비교 시작하기 | 가구비교",
    description: "원하는 가구를 편리하게 비교하고 매장 방문의 번거로움을 줄여보세요.",
    canonicalUrl: "/cta",
    lang: "ko",
    robots: "index,follow",
    ogTitle: "내게 맞는 가구, 합리적인 비교에서 시작하세요",
    ogDescription: "가격과 조건을 비교하고 내게 맞는 가구를 편리하게 찾아보세요.",
    status: "applied",
  },
];

export const mockCtaList: CtaButton[] = [
  {
    id: "cta-hero-start",
    label: "무료로 시작하기",
    href: "/screen",
    destinationKind: "start",
    destinationDescription: "가구를 비교할 때 겪는 불편을 확인하고 비교 과정을 시작합니다.",
    sectionId: "section-hero",
    variant: "primary",
    status: "active",
    clickCount: 24,
  },
  {
    id: "cta-problem-next",
    label: "계속",
    href: "/screen-2",
    destinationKind: "next_section",
    destinationDescription: "가구 가격과 조건을 더 간단하게 비교하는 방법을 확인합니다.",
    sectionId: "section-problem",
    variant: "primary",
    status: "active",
    clickCount: 19,
  },
  {
    id: "cta-solution-next",
    label: "계속",
    href: "/screen-3",
    destinationKind: "next_section",
    destinationDescription: "가구 비교로 얻을 수 있는 핵심 장점을 확인합니다.",
    sectionId: "section-solution",
    variant: "primary",
    status: "active",
    clickCount: 16,
  },
  {
    id: "cta-benefits-next",
    label: "계속",
    href: "/cta",
    destinationKind: "next_section",
    destinationDescription: "가구 비교를 시작할 수 있는 마지막 안내 화면으로 이동합니다.",
    sectionId: "section-benefits",
    variant: "primary",
    status: "active",
    clickCount: 13,
  },
  {
    id: "cta-final-start",
    label: "기획안 만들기",
    href: "/hero",
    destinationKind: "signup",
    destinationDescription: "가구 비교 서비스의 시작 화면에서 비교 흐름을 다시 시작합니다.",
    sectionId: "section-cta",
    variant: "primary",
    status: "active",
    clickCount: 9,
  },
];
